### ISSUE TITLE
Research Google Protobuf Framework

### ISSUE THREAD

**Issue by shalevv123** [ICST-Technion/F1CoreEngine#10]
Subtask of https://github.com/ICST-Technion/F1CoreEngine/issues/4

Research Google Protobuf framework in order to connect all of the components in the simulation loop:

1. Airsim
2. Cognata
3. Perception
4. State Estimation
5. Control

What programming language should we use?
What is the API?
How do we import all of the components of the simulation loop into the framework?

**Comment by yosefgoren** [comment]
**A quick preview of how protobuf will be used in our project;**
protobuf enables converting of data structures into binary format (serialize) in an automated, flexiable and extendible way.

To be more specific - We want communicate between different modules which might be written in different languages, might be on different machines, and also store these communications in a database.
protobuf handles these requirements  by generating corresponding classes for all targeted languages; it essentially compiles it's own special '.proto' language into whatever language we want, where each compiled class is compatible with it's variants of differing languages.

For example, if we want to send messages which describe an integer between a c++ application and a python application; we will define an integer 'message' within a '.proto' file, compile the '.proto' files once into c++, and once into python. Now we can '#include' the generated c++ into our c++ source code, and 'import' the generated python into our python source code.
At this point, the c++ and python applications have access to classes with getters, setters, encode and decode methods; such that encoding an object from c++ and sending it will allow decoding it from the python application (and vice versa).


As for **the specific questions**:
**What programming language should we use? C++**
- As described by the client; the most critical requirement from the backend evaluation loop is **the runtime**. Since we will not be using fortran, C++ comes to mind.
- **C++ is the language the team has the most experience with**; by far.
- C++ which seems to have the **most support with protobuf tools** from my research.

**What is the API?**
 - The API is described as 'messages' within the '.proto' file, each part of the team (i.e. Airsim, Cognata ...) should formalize the outputs/inputs of their module and describe it in the form of a '.proto' message. And use the generated classes to communicate their information upstream.

**How do we import all of the components of the simulation loop into the framework?**
 - protobuf can hardly be described as a framework since we will be importing the '.proto'-generated-classes into our codebase, and not the other way around. The specifics of generating the protobuf parts given our codebase have been described in the answer to the prior question.

*Google Protocol Buffer was a requirement by the client and thus swapping it for another "framework" wasn't considered
