### ISSUE TITLE
Research cloud hosting solutions

### ISSUE THREAD

**Issue by danielsl12** [ICST-Technion/F1CoreEngine#28]
Research cloud options so we could deploy our system in the cloud.
For example, AWS, Azure, Google cloud etc.
For each one check what is available in the free tier.
Also, check with @vMaroon if we might be able to get more than a free tier (maybe in Azure because the Technion already uses their services)

**Comment by vMaroon** [comment]
@danielsl12 I don't recall if we talked about this, but in general running on the cloud **is not** fitting for this project. You do want your architecture to follow cloud guidelines and for everything to run in easy-to-deploy containers, but the containers will be ran locally at the formula's on-prem servers (due to performance constraints).

**Comment by shalevv123** [comment]
Unrelevent
