### ISSUE TITLE
Research Dashboard Frontend Implementation Options

### ISSUE THREAD

**Issue by vMaroon** [ICST-Technion/F1CoreEngine#3]
Subtask of #2 

Research the different options for the dashboard's implementation:
* Programming language?
* Frameworks?
* Hosting services (client dashboard host)?

**Comment by danielsl12** [comment]
# Our choice: Grafana
## What is Grafana?
Grafana is a multi-platform open source analytics and interactive visualization web application. It provides charts, graphs, and alerts for the web when connected to supported data sources. It is expandable through a plug-in system. End users can create complex monitoring dashboards using interactive query builders. Grafana is divided into a front end and back end, written in TypeScript and Go, respectively.
## Advantages and Disadvantages
|Advantages | Disadvantages |
|-|-|
| <ul><li>Vast support for timeseries based graphs.</li><li>Large community and a lot of plugins created by the community</li><li>Flexibility and versatility</li><li>Vast support for different DBs</li><li>Easy to create plugins with numerous supported languages</li><li>Requires almost no programming</li></ul> | <ul><li>Hard to create non timeseries based graphs</li></ul>|
## Other options:
1. Create a dashboard from the grounds up in react.js. We didn't choose this option because it requires us to learn js from scratch and the react framework. Also, proven dashboard and monitoring solutions already exist (like Grafana), so why should we re-invent the wheel?
2.  Create a dashboard from the grounds up in Python. We didn't choose this option because we want to create a web client for the dashboard which is harder and cumbersome to do in python.

** We have seen other dashboarding solutions which were almost similar to Grafana which is "battle proven" and does what we needs, so we didn't research them further.
