### ISSUE TITLE
Research Dashboard Backend Implementation 

### ISSUE THREAD

**Issue by itay0611** [ICST-Technion/F1CoreEngine#6]
Subtask of #2  

Research the different options for the dashboard's backend implementation:

* Research available DB options.
* Research available data logger options. Related to #8.

**Comment by danielsl12** [comment]
# Our Choice: A server with restAPI/gRPC and TimescaleDB
## Diagram of the backend:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/63338501/203148990-a5a961c1-c902-4ecc-ab56-f8b0bf4e0048.png">

# Explanation:
The Formula main components create messages (see issue #8 ) which are sent to the backend server via restAPI / gRPC (we don't have the files as of writing this so it might be better to create with gRPC if we send proto files). Then, the server will do any analyzation required and will forward the analyzed message to the DB which is TimescaleDB.
The server will be written in GO.
## What is TimescaleDB?
TimescaleDB is an open-source time series database developed by Timescale Inc. It is written in C and extends PostgreSQL. TimescaleDB supports standard SQL queries and is a relational database. Additional SQL functions and table structures provide support for time series data oriented towards storage, performance, and analysis facilities for data-at-scale. 
### Advantages and Disadvantages
|Advantages | Disadvantages |
|-|-|
| <ul><li>Optimized for time series based data</li><li>Provides SQL functionality with known and tested PostgreSQL</li><li>Efficient space and speed wise</li><li>Can be used as real-time DB with relational features</li><li>Easy to get up and running</li><li>Easy to scale and reliable</li></ul> | <ul><li>As a relational DB it's important to model the data smart</li></ul>|
### Other options:
1. Another  popular TSDB option is InfluxDB. It offers more or less the same things as TimescaleDB (with arguably lesser performance) but the main reason we didn't choose InfluxDB as it requires us to learn it's own proprietary language and it gives us less options when querying the data, which is important because we don't know which kind of queries will be needed.
2. Another popular TSBD option is Prometheus. We didn't choose this option because it operates in a pull based fashion, which means it scrapes the data every x amount of time. In our case it is not sufficient because the simulations are brief, so we will lose a lot of datapoints.
3. Other SQL based DBs. Timescale DB is based on PosgreSQL which is tried and tested fast SQL DB, also, it is optimized to work with a timeseries which will be our main data, so there is no reason something else.

** We will model our backend code in a modular fashion, so we can change the DB easily and swiftly.

## What is Golang?
Go is a statically typed, compiled programming language designed at Google. It is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency. It is often referred to as Golang because of its former domain name, golang.org, but its proper name is Go.
### Advantages and Disadvantages
|Advantages | Disadvantages |
|-|-|
| <ul><li>Quick compilation and execution speed</li><li>No virtual machine needed</li><li>Portable and Lightweight goroutines that support concurrency</li><li>Accustomed to web services</li><li>Easy to learn</li></ul> | <ul><li>Lack of runtime safety</li></ul>|

### Other options:
1. Javascript. We did'nt choose Javascript because it is harder to learn and prone to mistakes
2. Python. Python is an interpreted language so naturally it is much slower than a compiled language. Furthermore, Python is last sutible to rest API.
  
** We kinda' wanted to use this opportunity to learn a new cool language 😉
